name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  index-package:
    name: Index Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5.0.1
        with:
          cache: false
      - name: go list
        run: GOPROXY=proxy.golang.org go list -m github.com/${{ github.repository }}@${{ github.ref_name }}
