name: Run tests

on:
  pull_request:
    branches: [main]
  pull_request_review_comment:
    types: [created, edited]
  schedule:
    - cron: "0 0 * * *"

jobs:

  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Setup Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version-file: "go.mod"

      - name: Install dependencies
        run: go get .

      - name: Run tests
        run: go test -v -shuffle=on ./...

  integration_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ./test/docker-compose.yml
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Build and create docker images
        run: docker compose --profile=test up --no-start
      
      - name: Run tests in container
        run: docker compose --profile=test up --exit-code-from=code --attach=code
